apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  hub: quay.io/jewertow
  tag: fips-203
  profile: ambient
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
  meshConfig:
    accessLogFile: /dev/stdout
#    meshMTLS:
#      ecdhCurves:
#      - X25519MLKEM768
#    tlsDefaults:
#      ecdhCurves:
#      - X25519MLKEM768
  values:
    pilot:
      env:
        COMPLIANCE_POLICY: "fips-203"
    global:
      variant: ""
    ztunnel:
      image: quay.io/jewertow/ztunnel-oqsprovider:latest
